name: Build tax_bot

on:
  push:
    branches:
      - main
      - 'release/v*.*.*'
  pull_request:
    branches:
      - main
      - 'release/v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build tax_bot
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "cargo/gh-actions-cache"

      - name: Run Build
        run: cargo build --verbose
